name: pull-request
on:
    pull_request:
        types: [opened, reopened]
jobs:
    assign:
        runs-on: ubuntu-latest
        steps:
            - uses: delivery-much/Guptarohit2003
              with:
                  token: ${{ secrets.GH_TOKEN }}
                  team-reviewers: Guptarohit2003
